### ISSUE TITLE
failed to extract PGT IOU from CAS validation response

### ISSUE THREAD

**Issue by paszczus** [iisys-hof/open-xchange-cas#2]
After modifying current code and get compiled jar, we are now having another problem:

`### storing original url: https://nowapoczta.foo.bar.pl/appsuite/
 com.openexchange.grizzly.method=GET
 com.openexchange.grizzly.queryString=<none>
 com.openexchange.grizzly.remoteAddress=10.59.146.75
 com.openexchange.grizzly.remotePort=35542
 com.openexchange.grizzly.requestURI=/ajax/casauth
 com.openexchange.grizzly.serverName=nowapoczta.foo.bar.pl
 com.openexchange.grizzly.servletPath=/ajax/casauth
 com.openexchange.grizzly.threadName=OXWorker-0000072
 com.openexchange.grizzly.userAgent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
 com.openexchange.request.trackingId=730564226-365282116
2017-05-25T17:10:34,071+0200 INFO  [OXTimer-0000072] com.openexchange.push.impl.balancing.reschedulerpolicy.PermanentListenerRescheduler.checkReschedule(PermanentListenerRescheduler.java:314)
Triggered rescheduling of permanent listeners incl. remote rescheduling
2017-05-25T17:10:34,071+0200 INFO  [OXTimer-0000072] com.openexchange.push.impl.balancing.reschedulerpolicy.PermanentListenerRescheduler.cancelTimerTask(PermanentListenerRescheduler.java:202)
Canceled timer task for rescheduling checks
2017-05-25T17:10:35,702+0200 ERROR [OXWorker-0000074] de.hofuniversity.iisys.ox.sso.CasLoginRequestHandler.handleLogin(CasLoginRequestHandler.java:454)
failed to extract PGT IOU from CAS validation response
 com.openexchange.grizzly.method=GET
 com.openexchange.grizzly.queryString=ticket=ST-451450-6MiRRryUcff349HAF4sP-login.foo.bar.pl
 com.openexchange.grizzly.remoteAddress=10.59.146.75
 com.openexchange.grizzly.remotePort=35546
 com.openexchange.grizzly.requestURI=/ajax/casauth
 com.openexchange.grizzly.serverName=nowapoczta.foo.bar.pl
 com.openexchange.grizzly.servletPath=/ajax/casauth
 com.openexchange.grizzly.threadName=OXWorker-0000074
 com.openexchange.grizzly.userAgent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
 com.openexchange.request.trackingId=730564226-365282117
2017-05-25T17:10:35,702+0200 WARN  [OXWorker-0000074] de.hofuniversity.iisys.ox.sso.CasLoginRequestHandler.handleRequest(CasLoginRequestHandler.java:170)
ClearPassHook Exception: 
 com.openexchange.grizzly.method=GET
 com.openexchange.grizzly.queryString=ticket=ST-451450-6MiRRryUcff349HAF4sP-login.foo.bar.pl
 com.openexchange.grizzly.remoteAddress=10.59.146.75
 com.openexchange.grizzly.remotePort=35546
 com.openexchange.grizzly.requestURI=/ajax/casauth
 com.openexchange.grizzly.serverName=nowapoczta.foo.bar.pl
 com.openexchange.grizzly.servletPath=/ajax/casauth
 com.openexchange.grizzly.threadName=OXWorker-0000074
 com.openexchange.grizzly.userAgent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
 com.openexchange.request.trackingId=730564226-365282117
java.lang.Exception: failed to process CAS validation response:

<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
	<cas:authenticationSuccess>
		<cas:user>paszczus@foo.bar.pl</cas:user>

		<cas:attributes>

		    
			 **<cas:mail>paszczus@foo.bar.pl</cas:mail>**
		    
			 **<cas:pesel>123456789</cas:pesel>**
		    
			 **<cas:usos_id>12345</cas:usos_id>**
		    
			 **<cas:givenname>Jan</cas:givenname>**
		    
			 **<cas:role>ROLE_ADMIN</cas:role>**
		    
			 **<cas:lastname>Kowalski</cas:lastname>**
		    

		</cas:attributes>
	</cas:authenticationSuccess>
</cas:serviceResponse>

	at de.hofuniversity.iisys.ox.sso.CasLoginRequestHandler.handleLogin(CasLoginRequestHandler.java:460)
	at de.hofuniversity.iisys.ox.sso.CasLoginRequestHandler.retrieveCredentials(CasLoginRequestHandler.java:303)
	at de.hofuniversity.iisys.ox.sso.CasLoginRequestHandler.handleRequest(CasLoginRequestHandler.java:165)
	at de.hofuniversity.iisys.ox.sso.CasAuthServlet.doGet(CasAuthServlet.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at de.hofuniversity.iisys.ox.sso.CasAuthServlet.service(CasAuthServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:147)
	at com.openexchange.http.grizzly.servletfilter.RequestReportingFilter.doFilter(RequestReportingFilter.java:132)
	at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:137)
	at com.openexchange.http.grizzly.servletfilter.WrappingFilter.doFilter(WrappingFilter.java:204)
	at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:137)
	at com.openexchange.http.grizzly.service.http.OSGiAuthFilter.doFilter(OSGiAuthFilter.java:140)
	at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:137)
	at org.glassfish.grizzly.servlet.FilterChainImpl.invokeFilterChain(FilterChainImpl.java:106)
	at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:224)
	at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:178)
	at com.openexchange.http.grizzly.service.http.OSGiMainHandler.service(OSGiMainHandler.java:223)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at com.openexchange.threadpool.internal.CustomThreadPoolExecutor$MDCProvidingRunnable.run(CustomThreadPoolExecutor.java:2570)
	at com.openexchange.threadpool.internal.CustomThreadPoolExecutor$Worker.runTask(CustomThreadPoolExecutor.java:840)
	at com.openexchange.threadpool.internal.CustomThreadPoolExecutor$Worker.run(CustomThreadPoolExecutor.java:867)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by rpeinl** [comment]
Unfortunately, it doesn't help to post an error that relates to a modified code. How should I trace that? Additionally, we currently have no resources to updating the module to the latest OX and CAS versions. Sorry.

**Comment by fly82** [comment]
I changed CasConfiguration.java
`LoginConfiguration conf = new LoginConfiguration(
            uiWebPath,
            sessiondAutoLogin,
            hashSource,
            httpAuthAutoLogin,
            defaultClient,
            clientVersion,
            errorPageTemplate,
            cookieExpiry,
            cookieForceHTTPS,
            insecure,
            ipCheck,
            ipCheckWhitelist,
            redirectIPChangeAllowed,
            ranges,
            disableTrimLogin,
            formLoginWithoutAuthId,
            isRandomTokenEnabled,
            false); // new: checkPunyCodeLoginString
`
to
`LoginConfiguration conf = new LoginConfiguration(
            uiWebPath,
            sessiondAutoLogin,
            hashSource,
            httpAuthAutoLogin,
            defaultClient,
            clientVersion,
            errorPageTemplate,
            cookieExpiry,
            cookieForceHTTPS,
            insecure,
            redirectIPChangeAllowed,
            disableTrimLogin,
            formLoginWithoutAuthId,
            isRandomTokenEnabled,
            false);`
and CasLoginRequestHandler.java
`                LoginRequestImpl logReq = new LoginRequestImpl(
                    credentials[0],
                    credentials[1],
                    clientIP,
                    userAgent,
                    authId,
                    client,
                    null,
                    hash,
                    HTTP_JSON,
                    headers,
                    cookies,
                    Tools.considerSecure(request, fLoginConf.isCookieForceHTTPS()),
                    request.getServerName(),
                    request.getServerPort(),
                    httpSessionId);`
to
`               LoginRequestImpl logReq = new LoginRequestImpl(
                    credentials[0],
                    credentials[1],
                    clientIP,
                    userAgent,
                    authId,
                    client,
                    null,
                    hash,
                    HTTP_JSON,
                    headers,
                    null,
                    cookies,
                    Tools.considerSecure(request, fLoginConf.isCookieForceHTTPS()),
                    request.getServerName(),
                    request.getServerPort(),
                    httpSessionId);`
